### ISSUE TITLE
api generation fails for hello world asyncapi spec

### ISSUE THREAD

**Issue by vhe1** [asyncapi/dotnet-nats-template#320]
#### Describe the bug
The generator fails with a simple api

#### How to Reproduce
Create a file "spec.yaml" with this code:
```
asyncapi: 2.5.0
info:
  title: Hello world application
  version: '0.1.0'
channels:
  hello:
    publish:
      message:
        payload:
          type: string
```

run the generator: `ag spec.yaml @asyncapi/dotnet-nats-template -o code`
observe the result:
```
Something went wrong:
SyntaxError: Unexpected token a in JSON at position 0
    at JSON.parse (<anonymous>)
    at modelTestRenderer (C:\Users\X1VHETZE\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\dotnet-nats-template\template\AsyncapiNatsClientTests\models\jsonModels.js:18:57)
    at Object.<anonymous> (C:\Users\X1VHETZE\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\generator-react-sdk\src\renderer\template.ts:23:18)
    at step (C:\Users\X1VHETZE\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\generator-react-sdk\lib\renderer\template.js:33:23)
    at Object.next (C:\Users\X1VHETZE\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\generator-react-sdk\lib\renderer\template.js:14:53)
    at fulfilled (C:\Users\X1VHETZE\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\generator-react-sdk\lib\renderer\template.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
Also, the AsyncapiNatsClient directory is empty.
 
#### Expected behavior
I expected a .net solution to appear, with a both projectes (client and tests) filled in.

#### Remarks
- `ag spec.yaml @asyncapi/markdown-template -o output` freates a prefectly usable documentation so I think it's not the spec.
- changing the api version to 2.0.0 doesn't change anything.

**Comment by jonaslagoni** [comment]
Thanks for the issue @vhe1, I haven't tested or worked much with payloads other than root payloads being `object` that should generate classes, because simple types with payloads are a bit harder to handle (alongside generating classes).

Not something I personally will look into soon, but happy to review a PR if you want to fix the issue :v:

**Comment by jonaslagoni** [comment]
On second thought, this is actually a different bug.

**Comment by vhe1** [comment]
The json workaround works! Thanks a lot! :-)

**Comment by gigkick** [comment]
...providing a JSON document fixes the issue -> can you please explain what to do in detail? I also see the error "Generator Error: Unexpected token a in JSON at position 0"

**Comment by jonaslagoni** [comment]
Had some dependent issues that needed to be fixed in Modelina natively, but that should be done, gonna give it a look later today, and ping you @JFCote for a review, thanks!
